# Generated by Django 5.2.3 on 2025-06-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='security_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
