# Generated by Django 5.2.3 on 2025-07-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policycontrol',
            name='policy',
            field=models.ForeignKey(db_column='sf_policy_template_id', on_delete=django.db.models.deletion.CASCADE, to='scrapinapp.policy'),
        ),
        migrations.AlterModelTable(
            name='controlclause',
            table='sf_control_clauses',
        ),
    ]
