# Generated by Django 5.2.3 on 2025-06-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0002_policy_security_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='regulation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
