# Generated by Django 5.2.3 on 2025-07-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0002_alter_policycontrol_policy_alter_controlclause_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policycontrol',
            name='control',
            field=models.ForeignKey(db_column='sf_control_id', on_delete=django.db.models.deletion.CASCADE, to='scrapinapp.control'),
        ),
    ]
