# Generated by Django 5.2.3 on 2025-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0003_certification_regulation_name_certification_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
