# Generated by Django 5.2.3 on 2025-06-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0004_policy_policy_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_gathered_from',
            field=models.CharField(blank=True, choices=[('TC', 'TrustCloud'), ('ER', 'Eramba')], max_length=2, null=True),
        ),
    ]
