# Generated by Django 5.2.3 on 2025-06-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0005_policy_policy_gathered_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='control_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
