# Generated by Django 5.2.3 on 2025-06-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0006_control_control_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='control_template',
        ),
    ]
