# Generated by Django 5.2.3 on 2025-07-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0007_remove_control_control_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='control_gathered_from',
            field=models.CharField(blank=True, choices=[('TC', 'TrustCloud'), ('ER', 'Eramba')], max_length=2, null=True),
        ),
    ]
