# Generated by Django 5.2.3 on 2025-07-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0008_control_control_gathered_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSyncingInProgress', models.BooleanField(default=False)),
            ],
        ),
    ]
