# Generated by Django 5.2.3 on 2025-07-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapinapp', '0009_checksync'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckSync',
        ),
        migrations.AddField(
            model_name='control',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
